# Generated by Django 2.0 on 2017-12-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
